<?php 

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group(array(
    'key' => 'group_step-by-step_module',
    'title' => __('StepByStep Module', 'modularity-step-by-step'),
    'fields' => array(
        0 => array(
            'key' => 'field_step-by-step_steps',
            'label' => __('Timeline Steps', 'modularity-step-by-step'),
            'name' => 'timeline_steps',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => __('Add steps to your timeline. Each step can be expanded to show content.', 'modularity-step-by-step'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_repeater_stylised_button' => 0,
            'layout' => 'block',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => __('Add Step', 'modularity-step-by-step'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_step-by-step_title',
                    'label' => __('Step Title', 'modularity-step-by-step'),
                    'name' => 'step_title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => __('Enter the title for this step (e.g., "Steg 1: Gör såhär")', 'modularity-step-by-step'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'allow_in_bindings' => 1,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_step-by-step_steps',
                ),
                1 => array(
                    'key' => 'field_step-by-step_content',
                    'label' => __('Step Content', 'modularity-step-by-step'),
                    'name' => 'step_content',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => __('Add the content that will be shown when this step is expanded.', 'modularity-step-by-step'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                    'parent_repeater' => 'field_step-by-step_steps',
                ),
                2 => array(
                    'key' => 'field_6949387375053',
                    'label' => __('Open by Default', 'modularity-step-by-step'),
                    'name' => 'open_by_default',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'allow_in_bindings' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                    'parent_repeater' => 'field_step-by-step_steps',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-step-by-step',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/step-by-step',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
    'acfe_autosync' => array(
        0 => 'json',
    ),
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));

}